[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 200
via_ir = true

[rpc_endpoints]
flow_testnet = "https://testnet.evm.nodes.onflow.org"

[etherscan]
flow_testnet = { key = "", url = "https://testnet.evm.flowscan.org/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
